### ISSUE TITLE
Support **mat** prefix

### ISSUE THREAD

**Issue by henriquecustodia** [1tontech/material2-snippets#4]
Material2 on beta.12 version works only with component prefix **mat**. Would be good update to support the current prefix. Thanks.

**Comment by imixtron** [comment]
prefix: `md` has been completely deprecated now. You have done an amazing work with the plugin, it is more helpful than the documentation itself. this issue should be prioritize as people are highly dependent on it, thank you and keep up the good work.

**Comment by jplew** [comment]
No shade intended towards this package, but Mikael Morlund's Angular 5
Snippets package already supports the 'mat-' prefix in case you need them
now.

**Comment by prog110** [comment]
Sorry,

Was away from work for sometime now.

Lemme check the release notes and make the changes.

Thanks

**Comment by prog110** [comment]
I have published a newer version. Can you please check and confirm

**Comment by henriquecustodia** [comment]
I think it is working fine :+1:

**Comment by prog110** [comment]
Thanks for verifying
